### PR TITLE
Add self to class

### LINKED ISSUE #31: Header needs to remain fixed on page
On smaller resolutions that are present here, there are some pages where scrolling will remove the header. This should be a relatively smaller fix, just needing to update the position and z-index used here.

### PR DESCRIPTION
**Pull request by justinr3**
Ability to add and remove self from courses. Tested on my local environment, works perfectly.

Also resolves #31, because why not. (Added after edit as a result of doing UI on this PR)

### CODE REVIEW

**Review by tamaraniac — CHANGES_REQUESTED** [review]
Nothing about this seems to prevent a user from enrolling themselves in the same class multiple times, which is a major issue. I also think it would be helpful if the interface displayed some sort of "successful enroll" feedback.

**Review by ddsnowboard — CHANGES_REQUESTED** [review]
I think it's a pretty big problem that the user gets no feedback whatsoever when they do something. We should probably take care of that, if nothing else. Although the fact that you can add yourself to a class more than once is also something of a problem.

**Review by rjaltman — CHANGES_REQUESTED** [review]
Generally, have the same perspective as everybody else about just getting some feedback in, and also making sure that multiple sign-ups don't happen. Other than that, the functionality looks like it is here, thanks for doing this!

I'll try to help out if it becomes really late on anything for the UI.

**Review by ddsnowboard — APPROVED** [review]

**Review by rjaltman — CHANGES_REQUESTED** [review]
I still have a weird interface thing going on, where it claims I unenroll from a class, that happens successfully but the tile does not disappear, and I can click on it again and get a success message for unenroll. It doesn't seem to do anything necessarily detrimental, but I would investigate a bit further just to make sure.

Also, sidebar won't be done at the end of this and instructors/organizers page will look a bit weird with sidebar not enabled. I'll make the changes soon but that's not what I'm marking this as blocking for. We'll open a separate PR for a finalized sidebar meant for all types of accounts.

**Review by tamaraniac — APPROVED** [review]

**Review by rjaltman — APPROVED** [review]
I think this is all good now, thanks for fixing that issue, Justin! 

All other first-draft sidebar changes are in this copy as well, and I think we are ready to merge.

**Review by ddsnowboard — APPROVED** [review]
This is way better. Great job on this. It looks great.

**Pull request merged**
